// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGBbSLgx-khSmEFJIXGS1FXAbhY-PJcg',
    appId: '1:738417424249:android:80ccd4bac0da8a57bba1a8',
    messagingSenderId: '738417424249',
    projectId: 'funz-quiz-9179a',
    storageBucket: 'funz-quiz-9179a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjqjzhrwrkW7HgOIcpA8DRykK0VfTbzc',
    appId: '1:738417424249:ios:32e4f626901090f0bba1a8',
    messagingSenderId: '738417424249',
    projectId: 'funz-quiz-9179a',
    storageBucket: 'funz-quiz-9179a.appspot.com',
    androidClientId: '738417424249-vf62sbgarlbsbgq5u8utnl7mc2smlgrt.apps.googleusercontent.com',
    iosClientId: '738417424249-e6i02eucgnnq444gqlmjsaugccd2j1t4.apps.googleusercontent.com',
    iosBundleId: 'com.funzquiz.funzQuiz',
  );
}
